### ISSUE TITLE
Proposal: `--force` option of `krew install` command

### ISSUE THREAD

**Issue by superbrothers** [kubernetes-sigs/krew#231]
`krew install` fails to install a plugin if it is already installed. However it is an inconvenience to have to delete it in advance when installing with a manifest file.

```sh
$ kubectl krew install --manifest <(curl -s -L https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/v2.1.2/open-svc.yaml)
Installing plugin: open-svc
W0629 11:32:42.107438    3762 install.go:128] Skipping plugin open-svc, it is already installed
```
Therefore, I proposes `--force` option of `krew install` which tries to install a plugin whether it is already installed or not.

```sh
$ kubectl krew install --manifest <(curl -s -L https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/v2.1.2/open-svc.yaml)
Installing plugin: open-svc
W0629 11:32:42.107438    3762 install.go:128] Skipping plugin open-svc, it is already installed
# With --force option
$ kubectl krew install --force --manifest <(curl -s -L https://github.com/superbrothers/kubectl-open-svc-plugin/releases/download/v2.1.2/open-svc.yaml)
Installing plugin: open-svc
Installed plugin: open-svc
```

If you approve this proposal, I'd like to implement it. WDYT?

**Comment by ahmetb** [comment]
I'm currently -2 to this proposal for several reasons (in no particular order):

- there are far too many software with `--force` flag today, usually points to bad design
- forceful installation doesn't mean anything (bad naming)
- ...at the same time it means too many things: Today, you propose it to be "install anyway", tomorrow someone might expand the definition to be also "ignore dependencies while installing". It's an overloaded term.
- it's useful only to plugin developers (who can easily just add a `krew remove ...;` to  the beginning of the command while testing) and doesn't impact the "user" persona.
- it's not necessary and not a big inconvenience. it's rather a nice-to-have, and we try not to implement nice-to-haves for a long time to avoid _feature creep_ and give these proposals a chance to prove if they're actually useful
- there's already a command to remove it, if we add a `--uninstall-first-if-installed` flag, it duplicates behavior (& issues, failure modes) of the `remove` command.
- the install command becomes harder to debug as it now also can do uninstall sometimes
- the integration test cases for `install` command now needs to get longer because now it can do uninstallation as well

Simply, there's too much to lose, there's little to gain.

**Comment by superbrothers** [comment]
Thank you for your comments:blush:

I understand your opinion well. By adding this option, plugin developers get a little convenience, but we will bring complex in `install` command at the same time. I agree "there's too much to lose".

**Comment by corneliusweig** [comment]
I'm mostly with Ahmet here. Normal users should never ever have any use for the `--force` flag and it introduces some complexity.

---

But it is somewhat awkward to first uninstall and then install via the `--manifest` option. To make this easier for plugin authors, we could add a script to `krew-index` where krew performs the install in a sandbox. That only requires to set the `KREW_ROOT` env var accordingly. To make this script more visible, it should should mentioned in the issue checklist on github. WDYT?

**Comment by ahmetb** [comment]
How big of a problem is this really? I'm personally not experiencing a high level of pain doing this flow. Once you write a bash command like `krew remove; krew install`, you just need to re run it multiple times while developing.

**Comment by corneliusweig** [comment]
I think it would be a nice convenience for plugin authors. Sure, you can always mess around with the actual krew installation, but it's not necessary. And knowing about `KREW_ROOT` is something we cannot expect from plugin authors. Are you worried about the maintenance and platform compatibility of such a script?

**Comment by ahmetb** [comment]
While I develop plugins, I just `krew remove` my plugin, and run `krew install --manifest=... --archive=...` and repeat until it works. Is this painful? (I'm mostly still trying to understand whether this is a real problem that warrants a solution.)

**Comment by corneliusweig** [comment]
No, this is not a big problem. Any serious plugin author can do that. But it is inconvenient, especially when an author releases new versions infrequently. Then he has to come up with these steps every time.
