### ISSUE TITLE
Proposal: clean untracked files while updating index

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#264]
Currently `krew update` (when called directly or indirectly via `install` or
`upgrade` commands) runs the following commands to ensure a _clean_ local
copy, so that we don't have to nuke/re-clone a repo every time.

- `git fetch -v`
- `git reset --hard '@{upstream}'`

However, these commands do not clean up untracked files.
I'm not sure if the _untracked files_ cause any issues yet but it feels like
we can also run `git clean -xfd` to remove untracked files from the local copy
in the `pkg/gitutil#EnsureUpdated()`.

/kind proposal
/priority backlog

**Comment by ahmetb** [comment]
@corneliusweig this is done in #202, right?

**Comment by corneliusweig** [comment]
No, #202 only took care of upgrading when the histories diverged (this PR introduced the `git reset --hard @{u}` part). The idea of this issue is to also remove untracked files with `git clean -xfd`.

This would restore the `index` folder to a pristine state regardless of what a krew user has done there. This could result in a user losing a file which he put into the index folder (for whatever reason). On the other hand I don't think we gain much by doing that additional cleanup. So I find it a bit inconclusive that we actually want to have this.

**Comment by ahmetb** [comment]
makes sense, thanks. I didn't read properly, sorry.
let's keep this open.
/remove-lifecycle stale
