### ISSUE TITLE
Simplify installation of Krew

### ISSUE THREAD

**Issue by scottilee** [kubernetes-sigs/krew#306]
Is it possible to simplify the installation of Krew via a one-line curl command like kubectl?

A brew option for Mac would be nice as well.

**Comment by corneliusweig** [comment]
Most of the installation already has a one-liner, see https://github.com/kubernetes-sigs/krew#bash-and-zsh. However, it will always be necessary to add `export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"` to the shell configuration. The reason is that you want to install plugins as unprivileged user, which requires to add the krew-bin folder to your `PATH`.

Even if krew were distributed as brew plugin, this last step would remain manual. Besides, installing krew via a package manager has other drawbacks, like
- you lose the ability to upgrade krew via krew
- if you install both krew-via-brew and krew-via-krew, which one should be run
- what should be the canonical `KREW_ROOT` when installed via pkg-manager?
- ...

@scottilee Do you see any other way how this could be simplified?

**Comment by balchua** [comment]
Quick question, is it necessary to have `git` when installing krew?

**Comment by corneliusweig** [comment]
@balchua git is not required for the installation itself, but it is a runtime dependency for krew. That's why the installation instructions mention this.

**Comment by ahmetb** [comment]
Ditto here. We want krew to manage krew so we don’t want to install krew through another package manager.

Re: git, we could use something like go-git to eliminate native git executable dependency, but I tend to think everyone who has kubectl installed also has git installed on their machine so I'm hesitant to make that change.

**Comment by scottilee** [comment]
Cool, just wanted some context on it since other tools like kubectl and kubectx have simpler installation methods. Thanks for the info!
