### ISSUE TITLE
krew does seem to work with bash aliases

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes-sigs/krew#434]
I have a bash alias like:

```alias kubectl='/usr/local/bin/kubectl --context "stage" --user "blake"'```

Unfortunately this doesn't work with krew:
```
$ kubectl krew
Error: unknown command "krew" for "kubectl"
Run 'kubectl --help' for usage.
```

If I open a fresh shell without aliases loaded it works fine. It also appears to break other kubectl plugins. Is there a possible work-around for overloaded aliases like this?

**Comment by ahmetb** [comment]
This is tracked in https://github.com/kubernetes/kubectl/issues/727.
Technically not a krew issue, but more like when you specify kubectl global options, currently plugin mechanism is not working at all.
/close

**Comment by corneliusweig** [comment]
This is a problem with the order of arguments to kubectl. When kubectl sees `--context` it assumes that it doesn't have to execute a plugin. Therefore, it only looks for builtin commands.

Looking at bash manual, you can find:

> For almost every purpose, aliases are superseded by shell functions.

So have can try this instead:
```sh
function kubectl {
    /usr/local/bin/kubectl "$1" --context "stage" --user "blake" "${@:2}"
}
```

However, it won't work, because krew does not accept `--context` as argument. So maybe rethink why you are using this alias and try `kubectx` instead?
