### ISSUE TITLE
Consider UPX to reduce size of `krew` binaries

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#610]
UPX (https://github.com/upx/upx) is a packer for binaries that supports the Linux, Darwin, and Windows platforms (notably no ARM). For my own plugins I've seen a size reduction to ~30% of the original size, so give and take a 3x improvement. Given that k8s plugins are usually quite bulky, it would be nice to pack our own binaries with UPX.

We could even make it a recommendation for plugin authors to do the same.

**Comment by ahmetb** [comment]
Usually these sort of utilities stripping binaries are known to have problems with Go in the long term —and they’re hard to debug. 

https://github.com/upx/upx/issues/222
https://github.com/upx/upx/issues/187

I am -1 currently since it will most likely break in the future at least for a subset of users and adds very little in return (plugin sizes aren’t a big deal for almost anyone).

**Comment by ahmetb** [comment]
I’ll close this since size isn't much of a problem for most people right now and UPX isn't an established tool. So I’d much rather keep it as a clean toolset.
/close
