### ISSUE TITLE
using functions from internal package

### ISSUE THREAD

**Issue by rajatjindal** [kubernetes-sigs/krew#617]
Hi @ahmetb 

we are using `sigs.k8s.io/krew/pkg/index/indexscanner` package from krew, but it seems like it has been moved to internal now.

any thoughts on how could we use it in tools like `krew-release-bot`

Thanks

**Comment by ahmetb** [comment]
Which method were you using? We can consider offering those.
But ideally how we scan plugins etc probably is an `internal` matter that we'd rather not support externally.

**Comment by rajatjindal** [comment]
i am using 

`indexscanner.ReadPluginFile(file)`
`indexscanner.ReadPluginFile(file)`
`indexscanner.DecodePluginFile(bytes.NewReader(spec))`
`validation.ValidatePlugin`

**Comment by ahmetb** [comment]
I think out of those we'd probably just make the validation pkg public potentially (since it helps people validate their manifests). For the rest, our `pkg/types` is already public, so you can directly use that type to parse into.

**Comment by rajatjindal** [comment]
yes, i believe exposing validation might be enough. the ReadPluginFile and DecodePluginFile are simple util functions to read/parse yaml file.

I can try to put up a PR for exposing validation pkg, if thats ok with you

**Comment by ahmetb** [comment]
/cc @corneliusweig 
thoughts?

@rajatjindal do you need to do the validation in the bot? we already do it in krew-index.

**Comment by rajatjindal** [comment]
We can defer the validations to krew but validations might still be useful for dryrun with krew release bot.

Also I think having those validations on krew release bot side mean we can fail the github action and provide feedback to user right there. 

However that wont be possible if we do validation after PR is opened

**Comment by ahmetb** [comment]
Yeah, that's valid. I'm hesitant of this because our exposed surface is very minimal right now, and most people who set up the bot already have a file checked in (e.g. already validated). By the time they see the error from the bot, it's already too late (their code was tagged).

So I recommend removing validations from krew-release-bot today, that way it can stay up-to-date with krew's validation code by not repeating it.

**Comment by rajatjindal** [comment]
hmm, i still think krew-release-bot should have some validation on its side. I agree that git tag would be done, but the user can atleast get the feedback on his repository when action fails without need to go to krew-index PR for verifying.

Requesting you to reconsider your recommendation.

**Comment by corneliusweig** [comment]
One thing that has come up a few times is that `release-bot` opens a PR, but the CI finds an error. Then it's up to the krew maintainers to close the PR, because the user cannot `/close`. The more of those can be caught early, the better I think. So that would speak for having the validation in `release-bot`.
However, our validation only does some basic syntax checks, and as @ahmetb said: most users already have a good template, so there's nothing to catch. So I think it's probably not worth it.

As a side-note: krew's validator is a standalone binary. You could also just build that and include in the container.

**Comment by ahmetb** [comment]
That’s a good point. The bot has definitely sent PRs that fail validation. Our validator tool is much more comprehensive than the validation funcs here and there. I recommend using it too.

**Comment by corneliusweig** [comment]
@rajatjindal would the container-packaged validator tool work for you?

**Comment by rajatjindal** [comment]
hey, sorry for the late response.

the container packaged validator will work for most of the cases. But if i remember correctly there are few users who uses krew-release-bot binary for the action.

so i guess i can use that. I will report back if i run into any issues with that.

Thanks for your patience and constant feedback

**Comment by corneliusweig** [comment]
@rajatjindal is running `krew-release-bot` directly (without being a GH action) something you endorse? Otherwise there's no need to restrict your options for the recommended setup.

**Comment by rajatjindal** [comment]
yeah i think it make sense. I'll add validator tool to the docker image and go from there.

thanks
