### ISSUE TITLE
`krew list` omits versions when called without a terminal

### ISSUE THREAD

**Issue by tyrken** [kubernetes-sigs/krew#619]
I'm trying to automate installing some kubectl plugins, and hoped to use `kubectl krew list` to query what versions of some plugins I'd previously installed via krew.

Unfortunately you have a hard-coded check for a terminal and show different output when called without one, see https://github.com/kubernetes-sigs/krew/blob/bc5bea24b76529802a5725d5648fabaf496cd3e9/cmd/krew/cmd/list.go#L49-L65

Could we have a command line option to the "list" sub-command to keep the same format as a shell sees, so I can parse it for the installed version numbers without hacks?  Assuming you want to keep the existing behaviour for backwards-compatibility that is - it was unexpected to me...

**Comment by ahmetb** [comment]
Yes, that’s by design. 

If you want to parse the output, we have an open issue suggesting adding a structured output format (such as json) option for “list”.

**Comment by ahmetb** [comment]
For posterity, the issue was #356, which was closed due to lack of interest.
If you can explain your use case a bit more (e.g. would json list work etc.) we can probably help.

**Comment by tyrken** [comment]
Hmm - a bit disappointing that you made the OP work so hard with over 150 comments in the discussion for #354 and #365 before it seems they, quite reasonably, gave up.

Might I suggest your proposal was over-complicated, as what he both suggested originally at the end of #354 and I'd hoped to find when I looked up the source to make the link above, was something like the 4 lines of Go in list.go with the Cobra flags.

I still think having different behaviour under a non-terminal is unexpected (other than cosmetics like dropping colourised output).

**Comment by ahmetb** [comment]
The current output of “list” is designed to back up the list of installed plugins to a file. Similarly “install” accepts this format when you feed in like <FILE. 

Admittedly the majority of the high number of comments happened because the person wasn’t familiar with the codebase. We can probably implement it in a simpler way if there is demand.

**Comment by corneliusweig** [comment]
@tyrken What problem are you trying to solve that requires to have a list of plugins with their respective versions?

I'm asking, because `krew` does not support to install a specific version of a plugin. It is only possible to install the latest version in the index for any plugin, which has served pretty well so far. I'd like to understand what you need to get done, so that we can put that into perspective.

FWIW, generating a list of installed plugins and installing everything from that list is something that our `list` and `install` subcommands solve pretty well.

**Comment by tyrken** [comment]
I'm running a system to distribute dev-tools to laptops, where we want to install a minimum version of a large number of tools & update them if we (later) decide to install an updated version.  Precise version that gets installed is probably not a problem but detecting the current version(s) installed is, for reporting and to choose whether to (re-)run krew or not.  Don't mind JSON/YAML/text-table but some sort of version string is the goal.

**Comment by ahmetb** [comment]
Technically you can read `$KREW_HOME/receipts/NAME.yaml`'s `spec.version` field to find the currently installed status. But since this has come up in #365 as well, I think it's a reasonable request to support the `list --format=[...]` option for these use cases.

**Comment by ahmetb** [comment]
/close 
since by design.
