### ISSUE TITLE
[releases] provide platform-specific binaries instead of tarball

### ISSUE THREAD

**Issue by laur89** [kubernetes-sigs/krew#622]
Would you guys consider uploading separate platform-specific binaries on github [release page](https://github.com/kubernetes-sigs/krew/releases/latest) instead of the single tarball?

**Comment by laur89** [comment]
yaml is needed as well, so this request is pointless, closing.

**Comment by corneliusweig** [comment]
@laur89 Can you explain why that would be better for you?

**Comment by ahmetb** [comment]
> yaml is needed as well, so this request is pointless, closing.

YAML is already on the Releases page.

**Comment by laur89** [comment]
One single binary would be better for me as i have a system maintenance/setup script that resolves the installables (be it binary, deb, or a tarball containing those) from any github repo releases page, and keeps track of the url; that way it can verify (by comparing the urls) whether the given version has already been downloaded/installed.

**Comment by zigarn** [comment]
@corneliusweig : because downloading the only 11MB file that I need for my platform would be less network/space consuming than downloading a 23MB tarball containing 6 files I don't care about.

Providing separate files and updating the install instruction to compute the right file to download instead of the right file to execute from the extracted tarball (no idea about this YAML file mentioned, not in the tarball or needed in the install instructions), e.g.:

```shell
(
  set -x; cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew-"${OS}_${ARCH}" &&
  KREW=./krew-"${OS}_${ARCH}" &&
  "$KREW" install krew
)
```

So, mostly, do like every other tools (like [minikube](https://github.com/kubernetes/minikube/releases), [kind](https://github.com/kubernetes-sigs/kind/releases), [docker-compose](https://github.com/docker/compose/releases), ...)

**Comment by ahmetb** [comment]
@zigarn do you mind opening a new issue proposing this, I think it's doable.

**Comment by corneliusweig** [comment]
Yes, I think it's worth reconsidering, since we added binaries for another architecture recently.

**Comment by zigarn** [comment]
Opened #697
