### ISSUE TITLE
Can krew be installed in a system-wide way?

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes-sigs/krew#623]
At my company we have many machines that are shared by many users. It would be nice to be able to install krew just once but still let users have their own plugin directories. Is this possible?

**Comment by ahmetb** [comment]
@2rs2ts Shared machines is definitely not a common use case but I think so.

All you need to do is place `kubectl-krew` binary to a PATH directory visible to all users (e.g. /usr/local/bin). However, you need to install updates to Krew yourself manually as well.

If you want to share plugins between users: You can set a $KREW_ROOT environment variable while installing krew, and keep setting that env variable in every bashrc/zshrc file. This way, Krew can look for a directory that's visible by all users (e.g. /var/opt/krew).

**Comment by 2rs2ts** [comment]
@ahmetb how do I get that binary? Will it be in a predictable location inside the release tarball? Plus it looks like krew wants to bootstrap itself, so is it really as simple as just placing the binary somewhere?

**Comment by ahmetb** [comment]
> how do I get that binary? Will it be in a predictable location inside the release tarball?

It currently is. We can't guarantee the location inside the tarball, but you'll find out there's only 1 binary in the tarball anyway. :) 

> Plus it looks like krew wants to bootstrap itself, so is it really as simple as just placing the binary somewhere?

Krew wants to bootstrap itself "if" you want Krew to be able to upgrade itself. But if you are OK with periodically (say, every 6 months) upgrading krew by changing your install scripts, then that's not needed. (In this install mode, `krew list` won't show `krew` itself as a plugin, but that's OK.)

**Comment by magf** [comment]
i'm confused. it's half-made tool.

not for system work.

**Comment by ahmetb** [comment]
@magf please elaborate what system work is.

**Comment by magf** [comment]
system means system-wide, not individual.
for example i'll check for system rights before installing and choose install-way personal or system if it possible, or ask how install.
sorry, ur tool is for personal use only.

**Comment by ahmetb** [comment]
You can set KREW_ROOT env var while installing and have it install anywhere on the system.

**Comment by magf** [comment]
thnx!
but I think it won't work for non-privileged users if it was installed by system user.
this is not intended for multi-user operation.
and I don't want to place $KREW_ROOT in /usr/local/bin where all default kubectl plugins are installed.
i see that's not multiuser tool by design.
be good for me, but bad for multiuser servers

**Comment by ahmetb** [comment]
> and I don't want to place $KREW_ROOT in /usr/local/bin where all default kubectl plugins are installed.

I don't know example of a tool that can install stuff on a machine in a shared way at a sharing a location on the filesystem without proper permissions among multiple users. Your problem is more about how directories and permissions work on the operating system. If you create a directory where every user can write, you can achieve this.
