### ISSUE TITLE
Automate dependency upgrades with dependabot

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#644]
Dependabot could automatically create PRs if some of our dependencies change. It doesn't work great with all dependencies, but it could at least alert us about new versions.
Some kubernetes subprojects seem to already use dependabot (some discussion: https://github.com/kubernetes/org/issues/945).

So WDYT? Should we try it out?

**Comment by ahmetb** [comment]
It definitely makes a lot more sense on an org like kubernetes-clients where language-specific repos are maintained. I'm not sure if it helps a lot for our case. Our dependency list is pretty minimal, so it might become more of a hassle/noise than helpful, since our dependencies probably update way more frequently than we ship (e.g. once or twice a year).

**Comment by corneliusweig** [comment]
One of my goals is to make us aware of available updates. But you have a good point that it will create a disproportionate amount of noise, given our infrequent releases.

So what about that: we add an item to our release procedure that reminds us about bumping versions. That way we don't have the noise and still get reminded of that chore when it becomes relevant.

**Comment by corneliusweig** [comment]
I tried this out in another project and dependabot creates quite a lot of noise. For us it's probably not worth it.
/close
