### ISSUE TITLE
Documentation missing how to install krew (and other plugins) offline (without internet access)

### ISSUE THREAD

**Issue by rafac92** [kubernetes-sigs/krew#663]
Hi, 

I was trying to install krew on a Machine which has no internet access but with the instructions I found here https://krew.sigs.k8s.io/docs/user-guide/setup/install/ I am not able to install it. It constantly tries to get the default index from github. 
I tried also to download the current content of the default directory. It did some further steps but then it again tries to do a git fetch which also fails.
Is there a way to do a offline installation of krew?

Kind Regards,
Rafa

**Comment by chriskim06** [comment]
So prior to krew v0.4.0 there was a somewhat offline install process. With the addition of custom indexes an issue came up and is detailed here https://github.com/kubernetes-sigs/krew/issues/630. The tl;dr version of that issue is that with the old way of installing krew, users wouldn't receive updates to krew itself in the future without some other changes and we ultimately settled on changing the install instructions to what they are now.

However, AFAIK there is no way to install plugins through krew without internet access. The default index that gets downloaded (krew-index) contains a folder of plugin manifests that krew uses to discover/install/update plugins. The manifests contain a URL that krew uses to download an archive containing the binary to be installed.

**Comment by ahmetb** [comment]
There are other package managers like Homebrew that package krew. That can help you install it semi-offline.

Alternatively, you can use command:

    krew install --manifest=krew.yaml --archive=krew.tar.gz

To install offline. But in this case krew won't be upgrading itself going forward as @chriskim06 said.

**Comment by ahmetb** [comment]
> However, AFAIK there is no way to install plugins through krew without internet access.

@chriskim06 To be clear, if you have access to plugin tarballs + manifest files, you can install them offline. All that does is practically just unpacking them at the right location and creating a symbolic link at ~/.krew/bin. 

I'm not sure if this is a desirable use case as it will not update the installed plugins. @rafac92 what exactly are you looking for here?

**Comment by rafac92** [comment]
Thanks for the explanations @ahmetb and @chriskim06. 
I only need krew for installing the kubelogin plugin, and as far as I understood, I could do that offline by getting krew.tar.gz and the krew.yaml file to install it via itself. (I guess that I need to have krew.tar.gz twice. Once to unpack the tar.gz to have the executable krew and seccond to pass it to krew)

Afterwards I assume that I can install kubelogin via 
`krew install --manifest=oidc-login.yaml --archive=kubelogin.zip`

where oidc-login.yaml is [this one](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/oidc-login.yaml)

**Comment by ahmetb** [comment]
Your understanding is correct.
/close
