### ISSUE TITLE
Can I install an explcit plugin version w krew?

### ISSUE THREAD

**Issue by RogerParkinson** [kubernetes-sigs/krew#714]
The plugin I installed has a problem, but the earlier ones are okay.
Is there a way to install an explicit version of a plugin, ie not the latest one?

**Comment by ahmetb** [comment]
@RogerParkinson unfortunately not, that's somewhat by design.
You can however manually install the plugin or take a harder path:

1. find the commit in krew-index repo that has the right version
2. cd $HOME/.krew/index/default
3. git reset --hard $COMMIT
4. kubectl krew install NAME --no-update-index

/kind question
/close
