### ISSUE TITLE
Download links for v0.4.2 release does not work

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/krew#726]
Hello,
The following links return 404

- https://github.com/kubernetes-sigs/krew/releases/download/v0.4.2/krew.tar.gz
- https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz

FYI, these links used to work for v0.4.1 release.

**Comment by chriskim06** [comment]
there was a recent change was made for [releasing separated archives for each platform](https://github.com/kubernetes-sigs/krew/pull/699). the [installation docs](https://github.com/kubernetes-sigs/krew/pull/700) were also recently updated (albeit a little bit after we released 0.4.2).

were you relying on those links in CI? this isn't the first issue filed for this, although the others were due to the docs not being updated immediately with the release. if you were relying on this in CI then maybe we should include the old bundled tar in the release artifacts in addition to the platform specific ones.

/cc @ahmetb 
/cc @corneliusweig
