### ISSUE TITLE
site: link for plugin star badges are broken

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#742]
https://krew.sigs.k8s.io/plugins/ star badges on this have this:

```
<a rel="nofollow" href="int128/kauthproxy">
<img src="https://img.shields.io/github/stars/int128/kauthproxy.svg?label=stars&amp;logo=github"></a>
```

and therefore go to a 404 page within the site.

/kind bug
/area docs
/help
/good-first-issue

**Comment by krishna2603** [comment]
Hi, I am new to contributing.
where can I find the code file? I mean the name of the file.

**Comment by rajatjindal** [comment]
I believe its here: https://github.com/kubernetes-sigs/krew/blob/78a78a6aa373893df3f127a6a6c6e29266b548db/site/functions/server/main.go#L172 and https://github.com/kubernetes-sigs/krew/blob/master/site/layouts/partials/footer.html#L67

**Comment by rajatjindal** [comment]
wondering if we should have it so that its git repo hosting agnostic (github vs gitlab e.g.)

**Comment by ahmetb** [comment]
I believe we only show the star badges for GitHub repositories, so we can add the github.com prefix. ￼￼

**Comment by Allianzcortex** [comment]
@ahmetb @rajatjindal Since this star badge is used for Github only , so I prefer not to change the response of the endpoint, it can be fixed as : 

Previously we redirect the badge : `<a href="https://github.com/${repo}`
Now we redirect the badge : `<a href="${repo}`

https://github.com/kubernetes-sigs/krew/blob/6edc70f3fac756ba908e746f007b48cb4b8ba8b8/site/layouts/partials/footer.html#L68

If you're satisfied with this approach then I can create a MR for it ( : -

**Comment by ahmetb** [comment]
Sounds good. We can test via Netlify preview.

**Comment by Allianzcortex** [comment]
kk ! /assign @Allianzcortex
