### ISSUE TITLE
Krew bash completion do not work on 0.4.3

### ISSUE THREAD

**Issue by wallsfantasy** [kubernetes-sigs/krew#769]
After I installed krew 0.4.3 I got a symlink in my local `.krew/bin` directory
```
~/.krew/bin/kubectl-krew
```
However, krew bash completion do not work unless I change the file name to `krew`.
```
~/.krew/bin/krew
```
But then `kubectl` will not recognize `kubectl krew`.

My workaround is to create symlink `krew` pointing to the original one.
```
~/.krew/bin/krew -> ./kubectl-krew
~/.krew/bin/kubectl-krew -> ~/.krew/store/krew/v0.4.3/krew
```

**Comment by wallsfantasy** [comment]
Hi, I'm on ubuntu 22.04 desktop.

While I'm exploring krew I tried `kubectl krew --help` and there's `completion` like this..
```
Usage:
  kubectl krew [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  ...
```
So I generated bash completion and put the  in `bash_completion.d`, like I normally would..
```
kubectl krew completion bash | sudo tee /etc/bash_completion.d/krew > /dev/null
source ~/.bashrc
```
I'd guess some of your lib might generate it for you.
But it quite nice at least I can't remember commands of every tools I'm working with :)

**Comment by ahmetb** [comment]
Oh, I see. You are install it yourself. 

I don't think we tested this. I guess the answer depends on the completion system but maybe there's a name you can give to the file make the completion work.

Or maybe it's because "krew" is hardcoded in the comp file. 

Either way, it's currently an unsupported use case. The shell completions for plugins is still being figured out in kubectl upstream.

**Comment by ahmetb** [comment]
Yeah, we can disable it. It could be useful for people who install directly via Homebrew (hence have `krew` binary directly) and Homebrew knows how to install completion scripts.

My experience in `kubectx` (I'm not even supporting the any linux officially) is that we get awful lot of confusion and issues stemming from people trying to install shell completion and running into issues. Based on my experience from there, there's no way to solve this cleanly across platforms×shells×distros×pkg managers and it's often a mess. 

FWIW the builtin kubectl feature is being worked on here. https://github.com/kubernetes/kubernetes/issues/74178#issuecomment-1020523792

**Comment by ahmetb** [comment]
(We're going out of scope of the issue here but) my plan was that if that proposal goes through we offer options in the plugin manifest to developers how they want to integrate with this feature. For example, we can offer a symlink feature where we link `kubectl_complete-krew` to `kubectl-krew`, but in the program, we can look at os.Args[0] to determine if we should print the completion script and exit. Some other plugin may choose to distribute a comp file (or a different executable to print a comp file).
