### ISSUE TITLE
Support Kerberos/Negotiate authentication for corporate proxies

### ISSUE THREAD

**Issue by vpinna80** [kubernetes-sigs/krew#788]
It seems that `krew` cannot be used behind a corporate proxy that requires Negotiate authentication.

`W0620 11:37:48.731292    7510 install.go:164] failed to install plugin "krew": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-linux_amd64.tar.gz": Get "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-linux_amd64.tar.gz": Proxy authentication required`

**Comment by ahmetb** [comment]
I am not sure if there's a clean way of solving this (like setting the HTTPS_PROXY env variable). I think any solution will involve bringing Kerberos dependency to this repo. 

If there's a way to add this without complicating the codebase for a small amount of users, I am interested in making it work. 

Looking at how other open source tools handle this and bringing ideas from there can help here.

**Comment by vpinna80** [comment]
Usually other tools delegate to curl for natively supporting Kerberos authentication.
This time I managed with including credentials in HTTPx_PROXY.

**Comment by ahmetb** [comment]
I suspect we'll skip supporting Kerberos/Negotiate authentication mostly because it has never come up, until this particular issue. I'm afraid delegating to `curl` won't work very well either, as we support Windows as well, and `curl` would be a net-new dependency and may break some people's workflows. 

If we get more evidence that there's a broad need for this, we can work on implementing it with a library like gokrb5.

**Comment by ahmetb** [comment]
/retitle Support Kerberos/Negotiate authentication for corporate proxies
