### ISSUE TITLE
Proposal:  kubectl krew list should not require a plugin index

### ISSUE THREAD

**Issue by nonproto** [kubernetes-sigs/krew#838]
When developing, or installing plugins as an archive.  Doing a `kubectl krew list` should show all installed plugins regardless of  the default plugin index not existing, and shouldn't attempt to force you to use it.

**Comment by chriskim06** [comment]
could you show the commands you ran that failed where you think they should succeed? i believe we allow krew to run without a default index (although krew-index ships as the default so it would need to be removed after the fact with `kubectl krew index remove default`)

**Comment by CarlosEsco** [comment]
`kubectl krew list`
comes back with 
`krew local plugin index is not initialized (run kubectl krew update)`

If you run this above then it works as designed but again requires the default plugin index. 
If you remove the default index with `kubectl krew index remove default` or by deleting the default folder in the krew install it comes back with 
`krew local plugin index is not initialized (run kubectl krew update)`

The only work around I've found so far is to `git init` in the default folder index.  Then `kubectl krew list` returns what is installed without setting the index.

**Comment by ahmetb** [comment]
I can repro it this way:
```
kubectl krew install tree whoami
kubectl krew index remove default --force
# no indexes exist at this point
kubectl krew list
# fails with error: krew local plugin index is not initialized (run "kubectl krew update
# even though some plugins are installed
```
however if you just add a random index, it starts working again:
```
kubectl krew index add other https://github.com/ahmetb/krew-index.git
kubectl krew list
# (shows previously installed plugins)
```

I don't know why we have this pre-run check in `list` command but it might be handling an edge case we forgot about at this point.

The part I don't understand is why would someone try to use krew without any indexes.
Can you clarify @CarlosEsco?

**Comment by CarlosEsco** [comment]
@ahmetb We are in an air gapped cluster without git repo access internally or externally and have to side load plugins with the --manifest --archive options.   

As for the pre-run check, i feel it should maybe warn, but continue at worst.  Instead of completely failing, or requires an empty git repository.

**Comment by chriskim06** [comment]
i feel like in that scenario you lose a lot of the benefits of krew since youre basically just manually installing binaries. i think you would only really have `uninstall` and `list` as the main usable functions and you can already do `kubectl plugin list` to somewhat make up for `kubectl krew list` (although it will only list what `kubectl-*` binaries are on your path).

**Comment by CarlosEsco** [comment]
Agree with both your points, we just found it easier for users managing the cluster to be able to see what is installed for kubernetes and to use them as "native" extensions vs having the binaries themselves.  We are also able to reuse the ansible plays pointing to the index for the non air gapped system.
